/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include "begin_code.h"
__BEGIN_DECLS
extern AG_StaticIcon esIconCircuit;
extern AG_StaticIcon esIconComponent;
extern AG_StaticIcon esIconInsertComponent;
extern AG_StaticIcon esIconRemoveComponent;
extern AG_StaticIcon esIconNode;
extern AG_StaticIcon esIconBranchToNode;
extern AG_StaticIcon esIconBranchToComponent;
extern AG_StaticIcon esIconStartSim;
extern AG_StaticIcon esIconStopSim;
extern AG_StaticIcon esIconSimSettings;
extern AG_StaticIcon esIconMesh;
extern AG_StaticIcon esIconExportToSpice;
extern AG_StaticIcon esIconSimDC;
extern AG_StaticIcon esIconSimAC;
extern AG_StaticIcon esIconSelectArrow;
extern AG_StaticIcon esIconSelectComponent;
extern AG_StaticIcon esIconInsertWire;
extern AG_StaticIcon esIconScope;
extern AG_StaticIcon esIconConsole;
extern AG_StaticIcon esIconPortEditor;
extern AG_StaticIcon esIconProximity;
__END_DECLS
#include "close_code.h"
