/* Agar icon reference file */
/* Generated by agarpaint 1.1 */

#include "begin_code.h"
__BEGIN_DECLS
extern AG_StaticIcon esIconCircuit;
extern AG_StaticIcon esIconComponent;
extern AG_StaticIcon esIconInsertComponent;
extern AG_StaticIcon esIconRemoveComponent;
extern AG_StaticIcon esIconNode;
extern AG_StaticIcon esIconBranchToNode;
extern AG_StaticIcon esIconBranchToComponent;
extern AG_StaticIcon esIconStartSim;
extern AG_StaticIcon esIconStopSim;
extern AG_StaticIcon esIconSimSettings;
extern AG_StaticIcon esIconMesh;
extern AG_StaticIcon esIconExportToSpice;
extern AG_StaticIcon esIconSimDC;
extern AG_StaticIcon esIconSimAC;
extern AG_StaticIcon esIconSelectArrow;
extern AG_StaticIcon esIconSelectComponent;
extern AG_StaticIcon esIconInsertWire;
extern AG_StaticIcon esIconScope;
extern AG_StaticIcon esIconConsole;
extern AG_StaticIcon esIconPortEditor;
extern AG_StaticIcon esIconProximity;
extern AG_StaticIcon esIconConstructionGeometry;
extern AG_StaticIcon esIconDiode;
extern AG_StaticIcon esIconResistor;
extern AG_StaticIcon esIconSPST;
extern AG_StaticIcon esIconSPDT;
extern AG_StaticIcon esIconLED;
extern AG_StaticIcon esIconLogicProbe;
extern AG_StaticIcon esIconInverter;
extern AG_StaticIcon esIconANDGate;
extern AG_StaticIcon esIconVsource;
extern AG_StaticIcon esIconVsquare;
extern AG_StaticIcon esIconVsine;
extern AG_StaticIcon esIconORGate;
extern AG_StaticIcon esIconXORGate;
extern AG_StaticIcon esIconGround;
__END_DECLS
#include "close_code.h"
