# Generic make include for all Edacious binaries.
# ex:syn=make

include ${TOP}/Makefile.config

PROJINCLUDES=	../configure.lua
PROG_LINKS=	es_core ag_math ag_core ag_gui ag_vg \
		pthreads SDL SDLmain opengl freetype

all: ${PROG}

CFLAGS+=-I${INCLDIR} \
	${AGAR_CFLAGS} ${AGAR_DEV_CFLAGS} ${AGAR_MATH_CFLAGS} ${AGAR_VG_CFLAGS}
LIBS+=	-L${TOP}/core/.libs -les_core \
	${AGAR_VG_LIBS} ${AGAR_MATH_LIBS} ${AGAR_DEV_LIBS} ${AGAR_LIBS}

include ${TOP}/mk/build.prog.mk
include ${TOP}/mk/build.man.mk
