TOP=	../..
include ${TOP}/Makefile.config

SHAREDIR=	${PREFIX}/share/agar-eda/Schematics/Sources
SHARESRC=	Vsine.eschem \
		Varb.eschem \
		Vsource.eschem \
		Vsquare.eschem \
		Vsweep.eschem

include ${TOP}/mk/build.prog.mk
