TOP=	..
include ${TOP}/Makefile.config

PROJECT=	"edacious"
PROJINCLUDES=	../configure.lua
PROG=		edacious
PROG_TYPE=	"GUI"
PROG_GUID=	"2dc24ff4-7e71-4a98-84db-0abc0af29030"

SRCS=	main.c
MAN1=	edacious.1

include ${TOP}/Makefile.prog
