#	$Csoft: Makefile,v 1.4 2004/09/29 04:12:13 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	circuit
SRCS=	analysis.c circuit.c spice.c kvl.c

CFLAGS+=${AGAR_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
