#	$Csoft: Makefile,v 1.1.1.1 2005/09/08 05:26:55 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	circuit
SRCS=	sim.c circuit.c spice.c kvl.c

CFLAGS+=${AGAR_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
