#	$Csoft: Makefile,v 1.2 2005/09/08 09:46:01 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

LIB=	circuit
SRCS=	sim.c circuit.c spice.c kvl.c mna.c

CFLAGS+=${AGAR_SC_CFLAGS} ${AGAR_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
