TOP=	..
include ${TOP}/Makefile.config

SHAREDIR=	${PREFIX}/share/edacious/Schematics
SUBDIR=		Digital \
		Sources
SHARESRC=	Ground.eschem \
		Resistor.eschem \
		Transistor.eschem \
		Diode.eschem \
		NMOS.eschem \
		PMOS.eschem \
		Capacitor.eschem \
		Inductor.eschem \
		NPN.eschem \
		PNP.eschem \
		SPST.eschem

include ${TOP}/mk/build.prog.mk
