TOP=	..
include ${TOP}/Makefile.config

SHAREDIR=	${PREFIX}/share/agar-eda/Schematics
SUBDIR=		Digital \
		Sources
SHARESRC=	Ground.eschem \
		Resistor.eschem \
		Transistor.eschem

include ${TOP}/mk/build.prog.mk
