#	$Csoft: Makefile,v 1.1.1.1 2004/06/05 06:57:11 vedge Exp $

TOP=	..
include ${TOP}/Makefile.config

XCF=	tools.xcf

DEN=		pixmaps.den
DEN_DIR=	pixmaps
DEN_NAME=	"Triton EDA pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2004 CubeSoft Communications, Inc."

include ${TOP}/mk/csoft.den.mk
