TOP=	..
include ${TOP}/Makefile.config

XCF=	tools.xcf

DEN=		pixmaps.den
DEN_DIR=	pixmaps
DEN_NAME=	"Agar-EDA pixmaps"
DEN_AUTHOR=	"vedge@"
DEN_COPYRIGHT=	"2004-2008 Hypertriton, Inc."

include ${TOP}/mk/build.den.mk
