#	$Csoft: Makefile,v 1.2 2004/09/02 05:59:11 vedge Exp $

TOP=	./..
include ${TOP}/Makefile.config

LIB=	tools
SRCS=	power.c \
	resistance.c \
	current.c \
	voltage.c \
	rmsvoltage.c \
	capacitance.c \
	weight.c \
	length.c \
	impedance.c \
	pressure.c \
	time.c \
	avreg.c \
	lm555.c

CFLAGS+=${AGAR_CFLAGS}

include ${TOP}/mk/csoft.lib.mk
