TOP=	..
include ${TOP}/Makefile.config

LIB=	schem
SRCS=	schem.c select_tool.c line_tool.c circle_tool.c point_tool.c \
	proximity_tool.c text_tool.c port.c

CFLAGS+=${AGAR_SC_CFLAGS} ${AGAR_CFLAGS}

include ${TOP}/mk/build.lib.mk
